{% set version = "2.1.5" %}
{% set name = "cypari2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a25865c34f20b1dc95830798e34ab6436e278b8e0c80dc7bf0ab34c5db03ab8

build:
  number: 2
  # cypari2 is generally compatible with Python 3.8 (but 2.1.3 and 2.1.4 have problems with that Python.)
  skip: true  # [win or py<39]
  script:
    - export PARI_SHARE="$PREFIX/share/pari"  # [unix]
    - python -m pip install --no-deps --ignore-installed --verbose .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - cython
    - python
    - pari
    - pip
    - cysignals
    - gmp
  run:
    - python
    - {{ pin_compatible('pari', max_pin='x.x') }}
    - cysignals
    - gmp

test:
  imports:
    - cypari2
  commands:
    - python -c "import doctest; import cypari2; doctest.testmod(cypari2, optionflags=doctest.ELLIPSIS|doctest.REPORT_NDIFF)"
    - test -f $SP_DIR/cypari2/auto_paridecl.pxd

about:
  home: https://github.com/sagemath/cypari2
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: An interface to the number theory library libpari

extra:
  recipe-maintainers:
    - maresb
    - isuruf
    - saraedum
