{% set version = "2.1.2" %}
{% set name = "cypari2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03cd45edab8716ebbfdb754e65fea72e873c73dc91aec098fe4a01e35324ac7a

build:
  number: 0
  skip: true  # [win]
  script:
    - python -m pip install --no-deps --ignore-installed --verbose .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - cython
    - python
    - pari
    - pip
    - cysignals
    - gmp
  run:
    - python
    - {{ pin_compatible('pari', max_pin='x.x') }}
    - cysignals
    - gmp

test:
  imports:
    - cypari2
  commands:
    - python -c "import doctest; import cypari2; doctest.testmod(cypari2, optionflags=doctest.ELLIPSIS|doctest.REPORT_NDIFF)"
    - test -f $SP_DIR/cypari2/auto_paridecl.pxd

about:
  home: https://github.com/defeo/cypari2
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'An interface to the number theory library libpari'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
