{% set version = "1.3.1" %}
{% set name = "cypari2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/defeo/cypari2/archive/{{ version }}.tar.gz
  sha256: a72cbcad2f45a04349cfd1d94eea66c823dda03e83fc72d8ca4c5d099679f3d9

build:
  number: 0
  skip: true  # [win]
  script:
    - python -m pip install --no-deps --ignore-installed --verbose .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - cython
    - python
    - pari >=2.9
    - pip
    - cysignals
    - gmp
  run:
    - python
    - {{ pin_compatible('pari', max_pin='x.x.x') }}
    - cysignals
    - gmp

test:
  imports:
    - cypari2
  commands:
    - python -c "import doctest; import cypari2; doctest.testmod(cypari2, optionflags=doctest.ELLIPSIS|doctest.REPORT_NDIFF)"
    - test -f $SP_DIR/cypari2/auto_paridecl.pxd

about:
  home: https://github.com/defeo/cypari2
  license: GPLv2+
  license_file: LICENSE
  summary: 'An interface to the number theory library libpari'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
